package allarraysquestions;

//filename: fixed-sliding-window.java
//Code Generated by Sidekick is for learning and experimentation purposes only.

public class FixedSlidingWindow {

 public static int maxSumSubarray(int[] arr, int k) {
     int n = arr.length;
     if (n < k) return -1;

     // Compute sum of first window
     int windowSum = 0;
     for (int i = 0; i < k; i++) {
         windowSum += arr[i];
     }

     int maxSum = windowSum;

     // Slide window: add next element, remove first element of previous window
     for (int i = k; i < n; i++) {
         windowSum += arr[i] - arr[i - k];
         maxSum = Math.max(maxSum, windowSum);
     }

     return maxSum;
 }

 public static void main(String[] args) {
     int[] arr = {2, 1, 5, 1, 3, 2};
     int k = 3;
     System.out.println("Max Sum: " + maxSumSubarray(arr, k)); // Output: 9
 }
}

